# Generated by Django 3.2.11 on 2022-01-10 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('thumbnail', models.FileField(help_text='Small img', upload_to='proj_thumbnails')),
                ('h1', models.CharField(help_text='Name of the project', max_length=200)),
                ('intro', models.TextField(help_text='Brief discription of the project', max_length=500)),
                ('madeWith', models.CharField(help_text='Technologies used for building  a project', max_length=200)),
                ('paragraph', models.TextField(help_text='Full discription of the project')),
                ('image', models.FileField(help_text='Full size img', upload_to='projects')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
