# Generated by Django 3.2.11 on 2022-01-11 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20220111_1610'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='madeWith',
            new_name='made_with',
        ),
    ]
